name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      id: tag_task
      run: |
        echo "TAG=$GITHUB_SHA" >> $GITHUB_OUTPUT 
          
    - name: upload image to ECR
      uses: appleboy/docker-ecr-action@master
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        registry: 072824470958.dkr.ecr.eu-central-1.amazonaws.com
        repo: myrepo
        region: eu-central-1
        tags: "${{steps.tag_task.outputs.TAG}}"
